name: Test exiting on failure

on:
  workflow_dispatch:
    inputs:
      mentions: 
        options: 
          - '@Carl'
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    name: '@Carl' 
    
    steps:
    - uses: actions/checkout@v1
    - name: '@Carl'
    - run: echo '@Carl Mention' 
    - name: Try to fail
      run: exit 1
    - name: Print message if we don't fail
      run: echo Should not get here
      
  # build2:
  #   strategy:
  #     matrix:
  #       os: [ubuntu-latest]
  #   runs-on: ${{ matrix.os }}
    
  #   steps:
  #   - uses: actions/checkout@v1
  #   - name: Try to fail
  #     run: exit 1
  #   - name: Print message if we don't fail
  #     run: echo Should not get here
      
  # build3:
  #   strategy:
  #     matrix:
  #       os: [ubuntu-latest]
  #   runs-on: ${{ matrix.os }}

    
  #   steps:
  #   - uses: actions/checkout@v1
  #   - name: Try to fail
  #     run: exit 1
  #   - name: Print message if we don't fail
  #     run: echo Should not get here
